<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Team Data Junkies - Chris Roche, Puri Rudick, and Ryan Kinney" />


<title>Case Study 1 by Data Junkies</title>

<script src="site_libs/jquery-1.11.3/jquery.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>
<link href="site_libs/anchor-sections-1.0/anchor-sections.css" rel="stylesheet" />
<script src="site_libs/anchor-sections-1.0/anchor-sections.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<style type="text/css">
  pre:not([class]) {
    background-color: white;
  }
</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>



<style type="text/css">
h1 {
  font-size: 34px;
}
h1.title {
  font-size: 38px;
}
h2 {
  font-size: 30px;
}
h3 {
  font-size: 24px;
}
h4 {
  font-size: 18px;
}
h5 {
  font-size: 16px;
}
h6 {
  font-size: 12px;
}
.table th:not([align]) {
  text-align: left;
}
</style>




<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
code {
  color: inherit;
  background-color: rgba(0, 0, 0, 0.04);
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
</style>


<style type="text/css">
/* padding for bootstrap navbar */
body {
  padding-top: 51px;
  padding-bottom: 40px;
}
/* offset scroll position for anchor links (for fixed navbar)  */
.section h1 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h2 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h3 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h4 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h5 {
  padding-top: 56px;
  margin-top: -56px;
}
.section h6 {
  padding-top: 56px;
  margin-top: -56px;
}
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #ffffff;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script>
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark it active
  menuAnchor.parent().addClass('active');

  // if it's got a parent navbar menu mark it active as well
  menuAnchor.closest('li.dropdown').addClass('active');
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  background: white;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "&#xe258;";
  border: none;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Purifect</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="aboutme.html">About Me</a>
</li>
<li>
  <a href="CaseStudy1_Group3_Combined.html">Case Study 1</a>
</li>
<li>
  <a href="https://purifect.shinyapps.io/BeerData/">Case Study 1 Shiny</a>
</li>
<li>
  <a href="CaseStudy1_Group3_Combined.html">Case Study 2</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div class="fluid-row" id="header">



<h1 class="title toc-ignore">Case Study 1 by Data Junkies</h1>
<h4 class="author">Team Data Junkies - Chris Roche, Puri Rudick, and Ryan Kinney</h4>

</div>


<p><a href="https://purifect.shinyapps.io/BeerData/">R Shiny App</a></p>
<p>The study of beers and breweries in the United States was conducted using over 2000 beers from more than 500 breweries.</p>
<p>Some of the focuses of this exploratory data analysis were placed on International Bitterness Units (IBU), Alcohol by volume (ABV), and regional differences with respect to states.</p>
<p>This analysis is useful for Budweiser future business decision.</p>
<div id="read-in-the-data-from-csv-files" class="section level3">
<h3>Read in the data from csv files</h3>
<pre class="r"><code>beerDataOrig = read.csv(&quot;Beers.csv&quot;,header = TRUE)
breweryDataOrig = read.csv(&quot;Breweries.csv&quot;,header = TRUE)</code></pre>
</div>
<div id="how-many-breweries-are-present-in-each-state" class="section level3">
<h3>1. How many breweries are present in each state?</h3>
<p>The number of breweries in each state as shown below. The darker color represents the higher number of breweries with number labeled.</p>
<p>The plot shows that Colorado has the most breweries in the country, which is 47 breweries.</p>
<pre class="r"><code>breweryDataOrig = as.data.frame(breweryDataOrig)

Breweries.in.each.state = breweryDataOrig %&gt;% group_by(State) %&gt;% tally()
names(Breweries.in.each.state)[1] &lt;- &quot;state&quot;
Breweries.in.each.state$state &lt;-
  str_replace_all(string=Breweries.in.each.state$state, 
                  pattern=&quot; &quot;, repl=&quot;&quot;)

centroid_labels &lt;- 
  utils::read.csv(system.file(&quot;extdata&quot;,
                              paste0(&quot;us_&quot;, &quot;states&quot;, &quot;_centroids.csv&quot;), 
                              package = &quot;usmap&quot;), stringsAsFactors = FALSE)

labels &lt;- 
  merge(x = centroid_labels, 
        y = Breweries.in.each.state, 
        by.x = &quot;abbr&quot;, 
        by.y = &quot;state&quot;, 
        all.x=TRUE)

names(labels)[6] &lt;- &quot;breweries_count&quot;

plot_usmap(data = Breweries.in.each.state, values = &quot;n&quot;, labels=FALSE) + 
  scale_fill_continuous(low = &quot;white&quot;, 
                        high = &quot;orange&quot;, 
                        name = &quot;# of Breweries&quot;, 
                        label = scales::comma) + 
  theme(legend.position = &quot;right&quot;) + 
  theme(panel.background = element_rect(colour = &quot;black&quot;)) + 
  labs(title = &quot;Number of Breweries by State&quot;) + 
  geom_text(data = labels, 
            ggplot2::aes(x = x, y = y, 
            label = scales::number(breweries_count,accuracy = 1)),
            color = &quot;black&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-2-1.png" width="672" /></p>
<p>Quick Facts:</p>
<ul>
<li>Colorado has the most breweries with 47</li>
<li>West Virginia, North Dakota, and South Dakota each have one brewery</li>
<li>Missouri (the home of Anheuser-Busch &amp; Budweiser) has 9 breweries (Ranks 20th)</li>
</ul>
</div>
<div id="merge-beer-data-with-the-breweries-data.-print-the-first-6-observations-and-the-last-six-observations-to-check-the-merged-file." class="section level3">
<h3>2. Merge beer data with the breweries data. Print the first 6 observations and the last six observations to check the merged file.</h3>
<p>Beer and breweries data are merged using Brewery_ID as an index.</p>
<p>Below are first and last six observations on the merged beer dataset.</p>
<pre class="r"><code>mergedBeerData &lt;- merge(x = beerDataOrig, y = breweryDataOrig,
                  by.x = &quot;Brewery_id&quot;, by.y = &quot;Brew_ID&quot;, all = TRUE)

names(mergedBeerData)[names(mergedBeerData)==&quot;Name.x&quot;] &lt;- &quot;Beer_name&quot;
names(mergedBeerData)[names(mergedBeerData)==&quot;Name.y&quot;] &lt;- &quot;Brewery_name&quot;

head(mergedBeerData)</code></pre>
<pre><code>##   Brewery_id     Beer_name Beer_ID   ABV IBU
## 1          1  Get Together    2692 0.045  50
## 2          1 Maggie&#39;s Leap    2691 0.049  26
## 3          1    Wall&#39;s End    2690 0.048  19
## 4          1       Pumpion    2689 0.060  38
## 5          1    Stronghold    2688 0.060  25
## 6          1   Parapet ESB    2687 0.056  47
##                                 Style Ounces       Brewery_name        City
## 1                        American IPA     16 NorthGate Brewing  Minneapolis
## 2                  Milk / Sweet Stout     16 NorthGate Brewing  Minneapolis
## 3                   English Brown Ale     16 NorthGate Brewing  Minneapolis
## 4                         Pumpkin Ale     16 NorthGate Brewing  Minneapolis
## 5                     American Porter     16 NorthGate Brewing  Minneapolis
## 6 Extra Special / Strong Bitter (ESB)     16 NorthGate Brewing  Minneapolis
##   State
## 1    MN
## 2    MN
## 3    MN
## 4    MN
## 5    MN
## 6    MN</code></pre>
<pre class="r"><code>tail(mergedBeerData)</code></pre>
<pre><code>##      Brewery_id                 Beer_name Beer_ID   ABV IBU
## 2405        556             Pilsner Ukiah      98 0.055  NA
## 2406        557  Heinnieweisse Weissebier      52 0.049  NA
## 2407        557           Snapperhead IPA      51 0.068  NA
## 2408        557         Moo Thunder Stout      50 0.049  NA
## 2409        557         Porkslap Pale Ale      49 0.043  NA
## 2410        558 Urban Wilderness Pale Ale      30 0.049  NA
##                        Style Ounces                  Brewery_name          City
## 2405         German Pilsener     12         Ukiah Brewing Company         Ukiah
## 2406              Hefeweizen     12       Butternuts Beer and Ale Garrattsville
## 2407            American IPA     12       Butternuts Beer and Ale Garrattsville
## 2408      Milk / Sweet Stout     12       Butternuts Beer and Ale Garrattsville
## 2409 American Pale Ale (APA)     12       Butternuts Beer and Ale Garrattsville
## 2410        English Pale Ale     12 Sleeping Lady Brewing Company     Anchorage
##      State
## 2405    CA
## 2406    NY
## 2407    NY
## 2408    NY
## 2409    NY
## 2410    AK</code></pre>
</div>
<div id="address-the-missing-values-in-each-column." class="section level3">
<h3>3. Address the missing values in each column.</h3>
<p>There are missing/empty values in three columns:</p>
<ul>
<li>ABV: 62 values missing</li>
<li>IBU: 1,005 values missing, and</li>
<li>Sty: 5 values missing</li>
</ul>
<p>Totaling in 1,007 rows with missing value.</p>
<pre class="r"><code>mergedBeerData$Style &lt;- 
  lapply(mergedBeerData$Style,
         function(x) if(identical(x,&quot;&quot;)) NA else x)


sapply(mergedBeerData, function(x) sum(is.na(x)))</code></pre>
<pre><code>##   Brewery_id    Beer_name      Beer_ID          ABV          IBU        Style 
##            0            0            0           62         1005            5 
##       Ounces Brewery_name         City        State 
##            0            0            0            0</code></pre>
<pre class="r"><code>row.has.na &lt;- apply(mergedBeerData, 1, function(x){any(is.na(x))})
sum(row.has.na)</code></pre>
<pre><code>## [1] 1007</code></pre>
<p>After filtering the missing/empty values out of the merged beer dataset, there are 1,405 rows of data in total that we work with.</p>
<pre class="r"><code># Filtered Merged Data
mergedBeerData.filtered &lt;- mergedBeerData[!row.has.na,]
nrow(mergedBeerData.filtered)</code></pre>
<pre><code>## [1] 1403</code></pre>
<pre class="r"><code>mergedBeerData.ABV_filtered = mergedBeerData %&gt;% filter(!is.na(ABV))
nrow(mergedBeerData.ABV_filtered)</code></pre>
<pre><code>## [1] 2348</code></pre>
<pre class="r"><code>mergedBeerData.IBU_filtered = mergedBeerData %&gt;% filter(!is.na(IBU))
nrow(mergedBeerData.IBU_filtered)</code></pre>
<pre><code>## [1] 1405</code></pre>
</div>
<div id="compute-the-median-alcohol-content-and-international-bitterness-unit-for-each-state.-plot-a-bar-chart-to-compare." class="section level3">
<h3>4.Compute the median alcohol content and international bitterness unit for each state. Plot a bar chart to compare.</h3>
<p>The median of Alcohol By Volume (ABV) and International Bitterness Units (IBU) for each state as shown below.</p>
<p>From the bar charts, Maine has the highest number for both ABV (0.067 or 6.7%) and IBU (61 unit).</p>
<pre class="r"><code># All rows NA filtered data
medianData &lt;- aggregate(mergedBeerData.filtered[, 4:5],
                        list(mergedBeerData.filtered$State), median)
names(medianData)[names(medianData)==&quot;Group.1&quot;] &lt;- &quot;State&quot;

# All ABV NA rows filtered
median.ABV &lt;- aggregate(mergedBeerData.ABV_filtered[, 4],
                        list(mergedBeerData.ABV_filtered$State), median)
names(median.ABV)[names(median.ABV)==&quot;Group.1&quot;] &lt;- &quot;State&quot;
names(median.ABV)[names(median.ABV)==&quot;x&quot;] &lt;- &quot;ABV&quot;

# All IBU NA rows filtered
median.IBU &lt;- aggregate(mergedBeerData.IBU_filtered[, 5],
                        list(mergedBeerData.IBU_filtered$State), median)
names(median.IBU)[names(median.IBU)==&quot;Group.1&quot;] &lt;- &quot;State&quot;
names(median.IBU)[names(median.IBU)==&quot;x&quot;] &lt;- &quot;IBU&quot;

# Merged data for ABV NA rows filtered and IBU NA rows filtered
median.ABV.IBU_filtered &lt;- merge(x = median.ABV, y = median.IBU,
                                 by = &quot;State&quot;, all = TRUE)
median.ABV.IBU_filtered$IBU[is.na(median.ABV.IBU_filtered$IBU)] &lt;- 0

g.mid &lt;- ggplot(median.ABV.IBU_filtered,aes(x=1, y = reorder(State,ABV))) +
  geom_text(aes(label=State)) +
  geom_segment(aes(x=0.94,xend=0.96,yend=State)) +
  geom_segment(aes(x=1.04,xend=1.062,yend=State)) +
  ggtitle(&quot;&quot;) +
  ylab(NULL) +
  scale_x_continuous(expand=c(0,0),limits=c(0.94,1.062)) +
  theme(axis.title=element_blank(),
        panel.grid=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        panel.background=element_blank(),
        axis.text.x=element_text(color=NA),
        axis.ticks.x=element_line(color=NA),
        plot.margin = unit(c(1,-1,1,-1), &quot;mm&quot;))

g1 &lt;- ggplot(data = median.ABV.IBU_filtered, aes(x = reorder(State,ABV), y = ABV, label = ABV)) +
  geom_bar(stat = &quot;identity&quot;, fill = &quot;sandybrown&quot;) + 
  ggtitle(&quot;Alcohol By Volume (ABV)&quot;) +
  geom_text(aes(y = ABV+0.004), 
            size = 3,
            vjust = .5) +
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(), 
        axis.text.x=element_text(color=NA),
        axis.ticks.x=element_line(color=NA),
        axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(), 
        legend.position = &quot;none&quot;,
        plot.title = element_text(hjust = 1),
        plot.margin = unit(c(1,0,1,0), &quot;mm&quot;)) +
  scale_y_reverse() +
  coord_flip(ylim = c(0.075,0.03))

g2 &lt;- ggplot(data = median.ABV.IBU_filtered, aes(x = reorder(State,ABV), y = IBU, fill = IBU, label=ifelse(IBU &lt; 1, &quot;NA&quot;, IBU))) +
  xlab(NULL) +
  geom_bar(stat = &quot;identity&quot;) +
  ggtitle(&quot;International Bitterness Units (IBU)&quot;) +
  geom_text(aes(y = IBU+4),
            size = 3,
            vjust = .5) +
  scale_fill_gradient2(low = &quot;grey25&quot;, 
                       high = &quot;black&quot;,
                       name = &quot;IBU&quot;) +
  theme(panel.background = element_blank(),
        axis.title.x = element_blank(), 
        axis.text.x=element_text(color=NA),
        axis.ticks.x=element_line(color=NA),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank(),
        legend.position = &quot;none&quot;,
        plot.margin = unit(c(1,5,1,0), &quot;mm&quot;)) +
  coord_flip(ylim = c(0,65))

gg1 &lt;- ggplot_gtable(ggplot_build(g1))
gg2 &lt;- ggplot_gtable(ggplot_build(g2))
gg.mid &lt;- ggplot_gtable(ggplot_build(g.mid))

grid.arrange(gg1,gg.mid,gg2,ncol=3,widths=c(4/9,1/9,4/9))</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-6-1.png" width="672" /></p>
<p>Combined the two bar charts together with radial stacked bar chart.</p>
<pre class="r"><code>median.ABV.IBU_filtered %&gt;%
  ggplot(aes(x = reorder(State,ABV))) +
  geom_col(aes(y = ABV*1000, fill = ABV*100)) +
  scale_fill_gradient2(low = &quot;white&quot;, 
                       high = &quot;orange&quot;,
                       name = &quot;Median ABV&quot;) +
  geom_text(aes(y = ABV*1000-8, label = round(ABV*100, 3)), color = &quot;chocolate4&quot;, size = 3) +
  new_scale_fill() +
  geom_col(aes(y = -IBU, fill = IBU)) +
  scale_fill_gradient2(low = &quot;grey25&quot;, 
                       high = &quot;black&quot;,
                       name = &quot;Median IBU&quot;) +
  geom_text(aes(y = -6, label = round(IBU, 0)), color = &quot;white&quot;, size = 3) +
  geom_text(aes(y = ABV*1000+10, label = State)) + 
  scale_y_continuous(limits = c(-70, 80)) +
  coord_polar() +
  theme_void() +
  labs(title = &quot;Median of Alcohol By Volume (ABV) and\nInternational Bitterness Units (IBU) for Each State&quot;,
       subtitle = &quot;   * The bar chart ordered clockwise by median ABV value\n   ** The darker color represents higher value of median ABV and IBU&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-7-1.png" width="672" /></p>
</div>
<div id="which-state-has-the-maximum-alcoholic-abv-beer-which-state-has-the-most-bitter-ibu-beer" class="section level3">
<h3>5. Which state has the maximum alcoholic (ABV) beer? Which state has the most bitter (IBU) beer?</h3>
<p>On average: - Colorado and Kentucky has the most alcoholic (6.25%) - Maine has the most bitter beer (61 IBU)</p>
<pre class="r"><code># arrange by ABV in descending order, print state for first observation
# arrange by ABV in descending order, print state for first observation
median.ABV.IBU_filtered$ABV.rank &lt;- dense_rank(-median.ABV.IBU_filtered$ABV)
with(median.ABV.IBU_filtered,
     median.ABV.IBU_filtered$State[median.ABV.IBU_filtered$ABV.rank == 1])</code></pre>
<pre><code>## [1] &quot; DC&quot; &quot; KY&quot;</code></pre>
<pre class="r"><code>median.ABV.IBU_filtered$IBU.rank &lt;- dense_rank(-median.ABV.IBU_filtered$IBU)
with(median.ABV.IBU_filtered,
     median.ABV.IBU_filtered$State[median.ABV.IBU_filtered$IBU.rank == 1])</code></pre>
<pre><code>## [1] &quot; ME&quot;</code></pre>
<p>By individual beers: - Colorado has the highest ABV beer at 12.8%, Lee Hill Series Vol. 5 by Upslope Brewing Company - Oregon has the most bitter beer at an IBU of 138, Bitter B**** Imperial IPA by Astoria Brewing Company</p>
<pre class="r"><code># arrange by ABV in descending order, print state for first observation
mergedBeerData$ABV.rank &lt;- dense_rank(-mergedBeerData$ABV)
filter(mergedBeerData,ABV.rank == 1)</code></pre>
<pre><code>##   Brewery_id                                            Beer_name Beer_ID   ABV
## 1         52 Lee Hill Series Vol. 5 - Belgian Style Quadrupel Ale    2565 0.128
##   IBU            Style Ounces            Brewery_name    City State ABV.rank
## 1  NA Quadrupel (Quad)   19.2 Upslope Brewing Company Boulder    CO        1</code></pre>
<pre class="r"><code>mergedBeerData$IBU.rank &lt;- dense_rank(-mergedBeerData$IBU)
filter(mergedBeerData,IBU.rank == 1)</code></pre>
<pre><code>##   Brewery_id                 Beer_name Beer_ID   ABV IBU
## 1        375 Bitter Bitch Imperial IPA     980 0.082 138
##                            Style Ounces            Brewery_name    City State
## 1 American Double / Imperial IPA     12 Astoria Brewing Company Astoria    OR
##   ABV.rank IBU.rank
## 1       23        1</code></pre>
</div>
<div id="comment-on-the-summary-statistics-and-distribution-of-the-abv-variable." class="section level3">
<h3>6. Comment on the summary statistics and distribution of the ABV variable.</h3>
<ul>
<li>The range of ABV’s is from a minimum of 0.1% to a maximum of 12.8%</li>
<li>The average ABV is 6% with a standard deviation of 1.4%</li>
</ul>
<pre class="r"><code>mergedBeerData.ABV_filtered %&gt;%
    summarize(mean=mean(ABV), 
              sd=sd(ABV), 
              median=median(ABV), 
              range=max(ABV)-min(ABV), 
              min(ABV), 
              max(ABV), 
              IQR=IQR(ABV))</code></pre>
<pre><code>##         mean         sd median range min(ABV) max(ABV)   IQR
## 1 0.05977342 0.01354173  0.056 0.127    0.001    0.128 0.017</code></pre>
<pre class="r"><code>mergedBeerData.ABV_filtered %&gt;% 
  ggplot(aes(x=ABV)) + 
  geom_histogram(binwidth = 0.004, color = &quot;black&quot;, fill = &quot;darkorange2&quot;) +
  labs(title = &quot;Alcohol by Volume (ABV)&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-10-1.png" width="672" /></p>
<ul>
<li>The range of IBU’s is from a minimum of 4 to a maximum of 138 unit</li>
<li>The average IBU is 43 unit with a standard deviation of 26</li>
</ul>
<pre class="r"><code>mergedBeerData.IBU_filtered %&gt;%
    summarize(mean=mean(IBU), 
              sd=sd(IBU), 
              median=median(IBU), 
              range=max(IBU)-min(IBU), 
              min(IBU), 
              max(IBU), 
              IQR=IQR(IBU))</code></pre>
<pre><code>##       mean       sd median range min(IBU) max(IBU) IQR
## 1 42.71317 25.95407     35   134        4      138  43</code></pre>
<pre class="r"><code>mergedBeerData.IBU_filtered %&gt;% 
  ggplot(aes(x=IBU)) + 
  geom_histogram(binwidth = 5, color = &quot;black&quot;, fill = &quot;darkorange2&quot;) +
  labs(title = &quot;International Bitterness Units (IBU)&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<pre class="r"><code>mergedBeerData.filtered %&gt;%
    summarize(mean=mean(ABV), 
              sd=sd(ABV), 
              median=median(ABV), 
              range=max(ABV)-min(ABV), 
              min(ABV), 
              max(ABV), 
              IQR=IQR(ABV))</code></pre>
<pre><code>##         mean         sd median range min(ABV) max(ABV)   IQR
## 1 0.05991875 0.01358475  0.057 0.098    0.027    0.125 0.018</code></pre>
</div>
<div id="is-there-an-apparent-relationship-between-the-bitterness-of-the-beer-and-its-alcoholic-content-draw-a-scatter-plot." class="section level3">
<h3>7. Is there an apparent relationship between the bitterness of the beer and its alcoholic content? Draw a scatter plot.</h3>
<p>From the scatter plot with a regression line, there is a positive correlation between a beer’s ABV and its IBU. There is strong evidence at the alpha = .05 level of significance to suggest that there is a linearly correlated relationship between a beer’s ABV and its IBU (p-value &lt;.0001), with Pearson’s Correlation Coefficient = 0.67 and r-square = 0.45.</p>
<pre class="r"><code>mergedBeerData.filtered %&gt;%
  ggplot(aes(x = ABV,y = IBU)) + 
  geom_jitter() + 
  ggtitle(&quot;ABV vs. IBU&quot;) + 
  geom_smooth(method=&quot;lm&quot;, se=F) + 
  stat_cor(label.y = 150, 
           aes(label = paste(..rr.label.., 
                             ..p.label.., 
                             sep = &quot;~`,`~&quot;))) +
  stat_regline_equation(label.y = 145) +
  theme_bw()</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<pre class="r"><code>cor.test(mergedBeerData.filtered$ABV,mergedBeerData.filtered$IBU)</code></pre>
<pre><code>## 
##  Pearson&#39;s product-moment correlation
## 
## data:  mergedBeerData.filtered$ABV and mergedBeerData.filtered$IBU
## t = 33.848, df = 1401, p-value &lt; 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6408842 0.6985369
## sample estimates:
##       cor 
## 0.6707224</code></pre>
</div>
<div id="use-knn-classification-to-investigate-the-relationship-between-ibu-and-abv-in-ales-and-ipas." class="section level3">
<h3>8. Use KNN classification to investigate the relationship between IBU and ABV in Ales and IPAs.</h3>
<p>Key results of the Confusion Matrix:</p>
<ul>
<li>Accuracy : 0.8232</li>
<li>95% CI : (0.7597, 0.8758)</li>
<li>Sensitivity : 0.8558</li>
<li>Specificity : 0.7792</li>
</ul>
<pre class="r"><code>mergedBeerData.filtered$AleStyle &lt;- 
  ifelse(grepl(&quot;IPA&quot;, mergedBeerData.filtered$Style, fixed = TRUE),&quot;IPA&quot;,
         ifelse(grepl(&quot;Ale&quot;, mergedBeerData.filtered$Style, fixed = TRUE),&quot;Ale&quot;,&quot;Other&quot;))

mergedBeerData.filtered$AleByName &lt;- 
  ifelse(grepl(&quot;India Pale Ale&quot;, mergedBeerData.filtered$Beer_name, fixed = TRUE),&quot;IPA&quot;,
         ifelse(grepl(&quot;IPA&quot;, mergedBeerData.filtered$Beer_name, fixed = TRUE),&quot;IPA&quot;,
                ifelse(grepl(&quot;Ale&quot;, mergedBeerData.filtered$Beer_name, fixed = TRUE),&quot;Ale&quot;,&quot;Other&quot;)))

aleBeerFiltered &lt;- mergedBeerData.filtered %&gt;% filter(AleByName == &quot;IPA&quot; | AleByName == &quot;Ale&quot;)

set.seed(4)
splitPerc = .7

trainIndices = sample(1:dim(aleBeerFiltered)[1], round(splitPerc * dim(aleBeerFiltered)[1]))
beerTrain = aleBeerFiltered[trainIndices,]
beerTest = aleBeerFiltered[-trainIndices,]

# run knn
classifications = knn(beerTrain[,4:5], beerTest[,4:5], beerTrain$AleByName, k = 5, prob = TRUE)
summary(classifications)</code></pre>
<pre><code>## Ale IPA 
## 104  77</code></pre>
<pre class="r"><code># Confusion Matrix
table(beerTest$AleByName, classifications)</code></pre>
<pre><code>##      classifications
##       Ale IPA
##   Ale  89  17
##   IPA  15  60</code></pre>
<pre class="r"><code>CM = confusionMatrix(table(beerTest$AleByName, classifications))
CM</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##      classifications
##       Ale IPA
##   Ale  89  17
##   IPA  15  60
##                                           
##                Accuracy : 0.8232          
##                  95% CI : (0.7597, 0.8758)
##     No Information Rate : 0.5746          
##     P-Value [Acc &gt; NIR] : 9.345e-13       
##                                           
##                   Kappa : 0.6371          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.8597          
##                                           
##             Sensitivity : 0.8558          
##             Specificity : 0.7792          
##          Pos Pred Value : 0.8396          
##          Neg Pred Value : 0.8000          
##              Prevalence : 0.5746          
##          Detection Rate : 0.4917          
##    Detection Prevalence : 0.5856          
##       Balanced Accuracy : 0.8175          
##                                           
##        &#39;Positive&#39; Class : Ale             
## </code></pre>
</div>
<div id="more-useful-information-expanding-knn-to-detect-non-ale-or-ipa-other-beers." class="section level3">
<h3>9. More useful information: Expanding KNN to detect non-Ale or IPA (other) beers.</h3>
<pre class="r"><code>set.seed(4)
splitPerc = .7

trainIndices.allType = sample(1:dim(mergedBeerData.filtered)[1], round(splitPerc * dim(mergedBeerData.filtered)[1]))
beerTrain.allType = mergedBeerData.filtered[trainIndices.allType,]
beerTest.allType = mergedBeerData.filtered[-trainIndices.allType,]

# run knn
classifications = knn(beerTrain.allType[,4:5], beerTest.allType[,4:5], beerTrain.allType$AleByName, k = 5, prob = TRUE)
summary(classifications)</code></pre>
<pre><code>##   Ale   IPA Other 
##    83    79   259</code></pre>
<pre class="r"><code># Confusion Matrix
table(beerTest.allType$AleByName, classifications)</code></pre>
<pre><code>##        classifications
##         Ale IPA Other
##   Ale    30   6    67
##   IPA     9  44    30
##   Other  44  29   162</code></pre>
<pre class="r"><code>CM.allType = confusionMatrix(table(beerTest.allType$AleByName, classifications))
CM.allType</code></pre>
<pre><code>## Confusion Matrix and Statistics
## 
##        classifications
##         Ale IPA Other
##   Ale    30   6    67
##   IPA     9  44    30
##   Other  44  29   162
## 
## Overall Statistics
##                                           
##                Accuracy : 0.5606          
##                  95% CI : (0.5117, 0.6086)
##     No Information Rate : 0.6152          
##     P-Value [Acc &gt; NIR] : 0.9903          
##                                           
##                   Kappa : 0.2309          
##                                           
##  Mcnemar&#39;s Test P-Value : 0.1458          
## 
## Statistics by Class:
## 
##                      Class: Ale Class: IPA Class: Other
## Sensitivity             0.36145     0.5570       0.6255
## Specificity             0.78402     0.8860       0.5494
## Pos Pred Value          0.29126     0.5301       0.6894
## Neg Pred Value          0.83333     0.8964       0.4785
## Prevalence              0.19715     0.1876       0.6152
## Detection Rate          0.07126     0.1045       0.3848
## Detection Prevalence    0.24466     0.1971       0.5582
## Balanced Accuracy       0.57273     0.7215       0.5874</code></pre>
</div>
<div id="more-useful-information-median-ibu-by-state" class="section level3">
<h3>9. More useful information: Median IBU by State</h3>
<pre class="r"><code>median.ABV.IBU_filtered = as.data.frame(median.ABV.IBU_filtered)

names(median.ABV.IBU_filtered)[1] &lt;- &quot;state&quot;
median.ABV.IBU_filtered$state &lt;-
  str_replace_all(string=median.ABV.IBU_filtered$state, 
                  pattern=&quot; &quot;, repl=&quot;&quot;)

centroid_labels &lt;- 
  utils::read.csv(system.file(&quot;extdata&quot;,
                              paste0(&quot;us_&quot;, &quot;states&quot;, &quot;_centroids.csv&quot;), 
                              package = &quot;usmap&quot;), stringsAsFactors = FALSE)

labels &lt;- 
  merge(x = centroid_labels, 
        y = median.ABV.IBU_filtered, 
        by.x = &quot;abbr&quot;, 
        by.y = &quot;state&quot;, 
        all.x=TRUE)

plot_usmap(data = median.ABV.IBU_filtered, values = &quot;IBU&quot;, labels=FALSE) + 
  scale_fill_continuous(low = &quot;white&quot;, 
                        high = &quot;darkgreen&quot;, 
                        name = &quot;Median IBU&quot;, 
                        label = scales::comma) + 
  theme(legend.position = &quot;right&quot;) + 
  theme(panel.background = element_rect(colour = &quot;black&quot;)) + 
  labs(title = &quot;Median IBU by State&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-15-1.png" width="672" /></p>
<p>Observation: There is a popular style of beer called a “West Coast IPA”, but the West Coast does not have more bitter beer than other regions on average.</p>
</div>
<div id="more-useful-information-median-abv-by-state" class="section level3">
<h3>9. More useful information: Median ABV by State</h3>
<pre class="r"><code>plot_usmap(data = median.ABV.IBU_filtered, values = &quot;ABV&quot;, labels=FALSE) + 
  scale_fill_continuous(low = &quot;white&quot;, 
                        high = &quot;darkblue&quot;, 
                        name = &quot;Median ABV&quot;, 
                        label = scales::comma) + 
  theme(legend.position = &quot;right&quot;) + 
  theme(panel.background = element_rect(colour = &quot;black&quot;)) + 
  labs(title = &quot;Median ABV by State&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-16-1.png" width="672" /></p>
<p>Observation: Utah and Arkansas had laws until 2020 limiting the alcohol content of beer.</p>
</div>
<div id="more-useful-information-beer-size-ounces-by-state" class="section level3">
<h3>9. More useful information: Beer Size (Ounces) by State</h3>
<p>There are 9 states that the biggest beer container size is only 12 ounces - Alaska - Alabama - Arkansas - DC - Georgia - North Dakota - South Dakota - Tennessee - West Virginia</p>
<p>It might be a good opportunity for Budweiser to launch a bigger size product in these states.</p>
<pre class="r"><code>max.size &lt;- aggregate(mergedBeerData[, 7],
                      list(mergedBeerData$State), max)
names(max.size)[names(max.size)==&quot;Group.1&quot;] &lt;- &quot;state&quot;
names(max.size)[names(max.size)==&quot;x&quot;] &lt;- &quot;max.Ounces&quot;

max.size$max.bin = cut(max.size$max.Ounces, 
                       breaks = c(0,11,12,16,32), 
                       labels = c(&quot;&lt; 12 Ounces&quot;,&quot;12 Ounces&quot;,&quot;16 Ounce&quot;, &quot;&gt;16 Ounce&quot;))

filter(max.size,max.bin == &quot;12 Ounces&quot;)</code></pre>
<pre><code>##   state max.Ounces   max.bin
## 1    AK         12 12 Ounces
## 2    AL         12 12 Ounces
## 3    AR         12 12 Ounces
## 4    DC         12 12 Ounces
## 5    GA         12 12 Ounces
## 6    ND         12 12 Ounces
## 7    SD         12 12 Ounces
## 8    TN         12 12 Ounces
## 9    WV         12 12 Ounces</code></pre>
<pre class="r"><code>max.size$state &lt;-
  str_replace_all(string=max.size$state, 
                  pattern=&quot; &quot;, repl=&quot;&quot;)

centroid_labels &lt;- 
  utils::read.csv(system.file(&quot;extdata&quot;,
                              paste0(&quot;us_&quot;, &quot;states&quot;, &quot;_centroids.csv&quot;), 
                              package = &quot;usmap&quot;), stringsAsFactors = FALSE)

labels &lt;- 
  merge(x = centroid_labels, 
        y = max.size, 
        by.x = &quot;abbr&quot;, 
        by.y = &quot;state&quot;, 
        all.x=TRUE)

plot_usmap(data = max.size, values = &quot;max.bin&quot;, labels=TRUE) + 
  scale_fill_manual(values = c(&quot;white&quot;, &quot;skyblue1&quot;, &quot;skyblue4&quot;), 
                    name = &quot;Max Container Size&quot;) +
  theme(legend.position = &quot;right&quot;) + 
  theme(panel.background = element_rect(colour = &quot;black&quot;),
        legend.text = element_text(size = 10)) + 
  labs(title = &quot;Maximum Beer Container Size by State&quot;)</code></pre>
<p><img src="CaseStudy1_Group3_Combined_files/figure-html/unnamed-chunk-17-1.png" width="672" /></p>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open')
  });
});
</script>

<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
